# Step 1 of migrating to the MySQL separate-database StudentModule backend
# Step 2 is in promote_csmh_db.yml
#
# Usage: AWS_PROFILE=myprofile ansible-playbook create_csmh_db.yml -i localhost, -e 'from_db=my-rds-identifier rds_name=env-dep-csm'

#NB: to set in promoter script:
#  multi-zone, username, password, size

- name: Create new StudentModule RDS instance
  hosts: all
  connection: local
  gather_facts: false
  vars:
    from_db:
    rds_name:
    region: us-east-1
    instance_type: db.m4.large

  tasks:
    - name: Validate arguments
      fail:
        msg: "One or more arguments were not set correctly: {{ item }}"
      when: not {{ item }}
      with_items:
        - from_db
        - rds_name

    - name: Create StudentModule RDS instance
      rds:
        command: replicate
        instance_name: "{{ rds_name }}"
        source_instance: "{{ from_db }}"
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        publicly_accessible: no
        wait: yes
        wait_timeout: 900
      register: created_db

    - name: Show created DB
      debug: var=created_db.instance
